### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ghost**
Insert offline links:
- jquery hosted by google
- working link to www.bootstrapcdn.com

### CODE REVIEW

**Comment by msurguy** [comment]
@DerHelmrich thanks for your PR! could you explain a bit more about what is the problem in current index.html? Is it not loading in some browsers or something else? Thanks!

**Comment by ghost** [comment]
After downloading it locally I've opened the index.html in a Webbrowser and it didn't load everything because of the missing links. I thought that I'm not the only one who tries it first and developes locally.

**Comment by msurguy** [comment]
@DerHelmrich I see, the problem with modifying those links from `//` to a hard coded 'http' value is that it will use http domain instead of https which is default on Github. If you want to be able to preview locally usually a small local server could be run (code editors like Webstorm does this by default). 

Mixing HTTPS and HTTP is not a good idea because some browsers will not proceed loading the page when insecure items are loaded so the only way to preview this locally without running the server would be to use HTTPS everywhere on the page for all resources. You can try out switching all assets to HTTPS and doing a PR with that if you still want to run locally without launching a server first. 

Thanks!

**Comment by ghost** [comment]
I don't use a local sever, but I'll do it from now on! So you can close this PR.

**Comment by msurguy** [comment]
@DerHelmrich Thank you for bringing this up!

**Pull request closed without merging**
